# Generated by Django 5.0.7 on 2024-07-19 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.PositiveIntegerField()),
                ('trip_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_api.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_api.route')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('status', models.CharField(default='Booked', max_length=75)),
                ('seat_number', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_api.trip')),
            ],
        ),
    ]
