# Generated by Django 5.0.7 on 2024-07-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_api', '0002_route_alter_bus_number_trip_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=6),
        ),
    ]
